(function () {
  window.LifeCalcSitePages = {
    siteUrlPlaceholder: "https://calc.underlab.work",
    pages: [
      "/",
      "/calculators/",
      "/calculators/finance/",
      "/calculators/life/",
      "/calculators/business/",
      "/calculators/search/",
      "/notices/",
      "/calculators/salary/",
      "/calculators/salary-slip/",
      "/calculators/loan/",
      "/calculators/loan-detail/",
      "/calculators/date/",
      "/calculators/date-calendar/",
      "/calculators/bmi/",
      "/calculators/age/",
      "/calculators/percent/",
      "/calculators/discount/",
      "/calculators/freelance/",
      "/calculators/freelance-detail/",
      "/calculators/vat/",
      "/calculators/margin/",
      "/calculators/breakeven/",
      "/calculators/settlement/",
      "/calculators/estimate/",
      "/calculators/fixedcost/",
      "/about/",
      "/privacy/",
      "/contact/",
    ],
  };
})();
